### ISSUE TITLE
Thunderbird-78.2.1: Error: $SRCDIR/comm/mail/installer/package-manifest.in:273: Missing file(s): bin/defaults/pref/all-gentoo.js

### ISSUE THREAD

**Issue by perfect7gentleman** [iadegesso/howl-gentoo-overlay#2]
```
34:43.11 Error: $SRCDIR/comm/mail/installer/package-manifest.in:273: Missing file(s): bin/defaults/pref/all-gentoo.js
34:43.46 Traceback (most recent call last):
34:43.46   File "/tmp/portage/mail-client/thunderbird-78.2.1-r1/work/thunderbird-78.2.1/toolkit/mozapps/installer/packager.py", line 249, in <module>
34:43.46     main()
34:43.46   File "/tmp/portage/mail-client/thunderbird-78.2.1-r1/work/thunderbird-78.2.1/toolkit/mozapps/installer/packager.py", line 208, in main
34:43.46     copier.add(mozpath.join(respath, 'removed-files'), removals)
34:43.46   File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
34:43.46     next(self.gen)
34:43.46   File "/tmp/portage/mail-client/thunderbird-78.2.1-r1/work/thunderbird-78.2.1/python/mozbuild/mozpack/errors.py", line 131, in accumulate
34:43.46     raise AccumulatedErrors()
34:43.46 mozpack.errors.AccumulatedErrors
34:43.48 gmake[3]: *** [/tmp/portage/mail-client/thunderbird-78.2.1-r1/work/thunderbird-78.2.1/toolkit/mozapps/installer/packager.mk:25: stage-package] Error 1
34:43.48 gmake[3]: Leaving directory '/tmp/portage/mail-client/thunderbird-78.2.1-r1/work/thunderbird-78.2.1/tbird/instrumented/comm/mail/installer'
34:43.48 gmake[2]: *** [/tmp/portage/mail-client/thunderbird-78.2.1-r1/work/thunderbird-78.2.1/toolkit/mozapps/installer/packager.mk:111: make-package] Error 2
34:43.48 gmake[2]: Leaving directory '/tmp/portage/mail-client/thunderbird-78.2.1-r1/work/thunderbird-78.2.1/tbird/instrumented/comm/mail/installer'
34:43.48 gmake[1]: *** [/tmp/portage/mail-client/thunderbird-78.2.1-r1/work/thunderbird-78.2.1/config/rules.mk:390: default] Error 2
34:43.48 gmake[1]: Leaving directory '/tmp/portage/mail-client/thunderbird-78.2.1-r1/work/thunderbird-78.2.1/tbird/instrumented/comm/mail/installer'
34:43.48 gmake: *** [/tmp/portage/mail-client/thunderbird-78.2.1-r1/work/thunderbird-78.2.1/comm/mail/build.mk:7: package] Error 2
```

**Comment by iadegesso** [comment]
I tested it with python 3.7... please try with that version of Python or send me the full build log.

Thanks

Iade

**Comment by perfect7gentleman** [comment]
I've slightly modified your ebuild as LLVM-11 is installed.
Test 1: commented that patch. -> PGO is failed.
Test 2: commented that patch and disable PGO. -> build is successful. 
```
mail-client/thunderbird-78.2.1-r1::pg_overlay was built with the following:
USE="clang custom-cflags custom-optimization eme-free gmp-autoupdate lightning lto pulseaudio system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-webp -bindist -debug -hardened -jack -pgo (-selinux) -test -wayland -wifi"
```
Test 3: enable that patch and PGO disabled -> build is successful.

**Comment by iadegesso** [comment]
In my Gentoo I have only llvm 9.x and 10.x. the 11th branch is still masked, so I don't use it... did you try building Thunderbird using llvm 10.x?

Iade

**Comment by perfect7gentleman** [comment]
With what flags do you have Thunderbird installed?
Concerning LLVM, I've already built Thunderbird-68.12.0 with LLVM-11.

**Comment by iadegesso** [comment]
Ok, these are my use flags:
`clang gmp-autoupdate jack lightning lto pulseaudio system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-webp wayland wifi -bindist -custom-cflags -custom-optimization -debug -eme-free -hardened -pgo -selinux -system-libvpx -test `

I also selected the `pgo` use flag but it never appears as built...

Iade

**Comment by perfect7gentleman** [comment]
because PGO is masked for Thunderbird.
```
 $ cat /etc/portage/profile/package.use.mask/thunderbird 
mail-client/thunderbird -pgo
```

**Comment by iadegesso** [comment]
> because PGO is masked for Thunderbird.

Oh, ok, I didn't looked why before :p Thanks


Coming back to the original isssue... can you share me the full build log?


Iade

**Comment by perfect7gentleman** [comment]
a bit later, currently I have limited access to my PC

**Comment by iadegesso** [comment]
Can you try with the newer minor version?

Iade

**Comment by perfect7gentleman** [comment]
https://gofile.io/d/tWKWC8 - build.log for 78.3.0
```
mail-client/thunderbird-78.3.0-r1::pg_overlay was built with the following:
USE="clang custom-cflags custom-optimization eme-free gmp-autoupdate lightning lto pulseaudio system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-webp -bindist -debug -hardened -jack -pgo (-selinux) -test -wayland -wifi" CPU_FLAGS_X86="avx2" L10N="ru -de -en-GB"
CFLAGS="-march=native -mtune=native -mllvm -polly -pipe -fdata-sections -ffunction-sections -fvectorize -fslp-vectorize -fomit-frame-pointer -fno-common -fno-plt -fno-stack-protector -fno-unwind-tables"
CXXFLAGS="-march=native -mtune=native -mllvm -polly -pipe -fdata-sections -ffunction-sections -fvectorize -fslp-vectorize -fomit-frame-pointer -fno-common -fno-plt -fno-stack-protector -fno-unwind-tables -stdlib=libc++"
FEATURES="distlocks metadata-transfer news protect-owned xattr preserve-libs sfperms merge-sync config-protect-if-modified network-sandbox multilib-strict ipc-sandbox ebuild-locks usersandbox binpkg-logs strict assume-digests parallel-install unknown-features-warn binpkg-docompress parallel-fetch unmerge-orphans sandbox qa-unresolved-soname-deps userpriv unmerge-logs binpkg-dostrip pid-sandbox userfetch fixlafiles usersync"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--gc-sections -Wl,--icf=all -Wl,--lto-O3 -fuse-ld=lld -stdlib=libc++ -rtlib=compiler-rt -unwindlib=libunwind -s -march=native -mtune=native -mllvm -polly -pipe -fdata-sections -ffunction-sections -fvectorize -fslp-vectorize -fomit-frame-pointer -fno-common -fno-plt -fno-stack-protector -fno-unwind-tables -Wl,-rpath=/usr/lib64/thunderbird,--enable-new-dtags -Wl,--compress-debug-sections=zlib"
```
